/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zombie_core_znet_PortMapper */

#ifndef _Included_zombie_core_znet_PortMapper
#define _Included_zombie_core_znet_PortMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _discover
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_znet_PortMapper__1discover
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_znet_PortMapper__1cleanup
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _igd_found
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_znet_PortMapper__1igd_1found
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _add_mapping
 * Signature: (IILjava/lang/String;Ljava/lang/String;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_znet_PortMapper__1add_1mapping
  (JNIEnv *, jclass, jint, jint, jstring, jstring, jint, jboolean);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _remove_mapping
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_znet_PortMapper__1remove_1mapping
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _fetch_mappings
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_znet_PortMapper__1fetch_1mappings
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _num_mappings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_znet_PortMapper__1num_1mappings
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _get_mapping
 * Signature: (I)Lzombie/core/znet/PortMappingEntry;
 */
JNIEXPORT jobject JNICALL Java_zombie_core_znet_PortMapper__1get_1mapping
  (JNIEnv *, jclass, jint);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _get_gateway_info
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zombie_core_znet_PortMapper__1get_1gateway_1info
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_PortMapper
 * Method:    _get_external_address
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zombie_core_znet_PortMapper__1get_1external_1address
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
