/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zombie_core_raknet_RakNetPeerInterface */

#ifndef _Included_zombie_core_raknet_RakNetPeerInterface
#define _Included_zombie_core_raknet_RakNetPeerInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef zombie_core_raknet_RakNetPeerInterface_ID_NEW_INCOMING_CONNECTION
#define zombie_core_raknet_RakNetPeerInterface_ID_NEW_INCOMING_CONNECTION 19L
#undef zombie_core_raknet_RakNetPeerInterface_ID_DISCONNECTION_NOTIFICATION
#define zombie_core_raknet_RakNetPeerInterface_ID_DISCONNECTION_NOTIFICATION 21L
#undef zombie_core_raknet_RakNetPeerInterface_ID_INCOMPATIBLE_PROTOCOL_VERSION
#define zombie_core_raknet_RakNetPeerInterface_ID_INCOMPATIBLE_PROTOCOL_VERSION 25L
#undef zombie_core_raknet_RakNetPeerInterface_ID_CONNECTED_PING
#define zombie_core_raknet_RakNetPeerInterface_ID_CONNECTED_PING 0L
#undef zombie_core_raknet_RakNetPeerInterface_ID_UNCONNECTED_PING
#define zombie_core_raknet_RakNetPeerInterface_ID_UNCONNECTED_PING 1L
#undef zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_LOST
#define zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_LOST 22L
#undef zombie_core_raknet_RakNetPeerInterface_ID_ALREADY_CONNECTED
#define zombie_core_raknet_RakNetPeerInterface_ID_ALREADY_CONNECTED 18L
#undef zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_DISCONNECTION_NOTIFICATION
#define zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_DISCONNECTION_NOTIFICATION 31L
#undef zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_CONNECTION_LOST
#define zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_CONNECTION_LOST 32L
#undef zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_NEW_INCOMING_CONNECTION
#define zombie_core_raknet_RakNetPeerInterface_ID_REMOTE_NEW_INCOMING_CONNECTION 33L
#undef zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_BANNED
#define zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_BANNED 23L
#undef zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_ATTEMPT_FAILED
#define zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_ATTEMPT_FAILED 17L
#undef zombie_core_raknet_RakNetPeerInterface_ID_NO_FREE_INCOMING_CONNECTIONS
#define zombie_core_raknet_RakNetPeerInterface_ID_NO_FREE_INCOMING_CONNECTIONS 20L
#undef zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_REQUEST_ACCEPTED
#define zombie_core_raknet_RakNetPeerInterface_ID_CONNECTION_REQUEST_ACCEPTED 16L
#undef zombie_core_raknet_RakNetPeerInterface_ID_INVALID_PASSWORD
#define zombie_core_raknet_RakNetPeerInterface_ID_INVALID_PASSWORD 24L
#undef zombie_core_raknet_RakNetPeerInterface_ID_PING
#define zombie_core_raknet_RakNetPeerInterface_ID_PING 28L
#undef zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_OPEN_CHANNEL_REQUEST
#define zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_OPEN_CHANNEL_REQUEST 44L
#undef zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_OPEN_CHANNEL_REPLY
#define zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_OPEN_CHANNEL_REPLY 45L
#undef zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_CLOSE_CHANNEL
#define zombie_core_raknet_RakNetPeerInterface_ID_RAKVOICE_CLOSE_CHANNEL 46L
#undef zombie_core_raknet_RakNetPeerInterface_ID_USER_PACKET_ENUM
#define zombie_core_raknet_RakNetPeerInterface_ID_USER_PACKET_ENUM 134L
#undef zombie_core_raknet_RakNetPeerInterface_PacketPriority_IMMEDIATE
#define zombie_core_raknet_RakNetPeerInterface_PacketPriority_IMMEDIATE 0L
#undef zombie_core_raknet_RakNetPeerInterface_PacketPriority_HIGH
#define zombie_core_raknet_RakNetPeerInterface_PacketPriority_HIGH 1L
#undef zombie_core_raknet_RakNetPeerInterface_PacketPriority_MEDIUM
#define zombie_core_raknet_RakNetPeerInterface_PacketPriority_MEDIUM 2L
#undef zombie_core_raknet_RakNetPeerInterface_PacketPriority_LOW
#define zombie_core_raknet_RakNetPeerInterface_PacketPriority_LOW 3L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE 0L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE_SEQUENCED
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE_SEQUENCED 1L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE 2L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_ORDERED
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_ORDERED 3L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_SEQUENCED
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_SEQUENCED 4L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE_WITH_ACK_RECEIPT
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_UNRELIABLE_WITH_ACK_RECEIPT 5L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_WITH_ACK_RECEIPT
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_WITH_ACK_RECEIPT 6L
#undef zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_ORDERED_WITH_ACK_RECEIPT
#define zombie_core_raknet_RakNetPeerInterface_PacketReliability_RELIABLE_ORDERED_WITH_ACK_RECEIPT 7L
#undef zombie_core_raknet_RakNetPeerInterface_ConnectionType_Disconnected
#define zombie_core_raknet_RakNetPeerInterface_ConnectionType_Disconnected 0L
#undef zombie_core_raknet_RakNetPeerInterface_ConnectionType_UDPRakNet
#define zombie_core_raknet_RakNetPeerInterface_ConnectionType_UDPRakNet 1L
#undef zombie_core_raknet_RakNetPeerInterface_ConnectionType_Steam
#define zombie_core_raknet_RakNetPeerInterface_ConnectionType_Steam 2L
/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    Init
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_Init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    Startup
 * Signature: (ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_Startup
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_Shutdown
  (JNIEnv *, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetServerIP
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetServerIP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetServerPort
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetServerPort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetClientPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetClientPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    Connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_Connect
  (JNIEnv *, jobject, jstring, jint, jstring, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    ConnectToSteamServer
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_ConnectToSteamServer
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetServerIP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetServerIP
  (JNIEnv *, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetClientSteamID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetClientSteamID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetClientOwnerSteamID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetClientOwnerSteamID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetIncomingPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetIncomingPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetTimeoutTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetTimeoutTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetMaximumIncomingConnections
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetMaximumIncomingConnections
  (JNIEnv *, jobject, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetOccasionalPing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetOccasionalPing
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    SetUnreliableTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_SetUnreliableTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    TryReceive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_raknet_RakNetPeerInterface_TryReceive
  (JNIEnv *, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    nativeGetData
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_nativeGetData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    sendNative
 * Signature: (Ljava/nio/ByteBuffer;IIIBJZ)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_sendNative
  (JNIEnv *, jobject, jobject, jint, jint, jint, jbyte, jlong, jboolean);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    getGuidFromIndex
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_zombie_core_raknet_RakNetPeerInterface_getGuidFromIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    getGuidOfPacket
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_zombie_core_raknet_RakNetPeerInterface_getGuidOfPacket
  (JNIEnv *, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    getIPFromGUID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zombie_core_raknet_RakNetPeerInterface_getIPFromGUID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    disconnect
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakNetPeerInterface_disconnect
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetNetStatistics
 * Signature: (J)Lzombie/core/znet/ZNetStatistics;
 */
JNIEXPORT jobject JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetNetStatistics
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetAveragePing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetAveragePing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetLastPing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetLastPing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetLowestPing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetLowestPing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetMTUSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetMTUSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetConnectionsNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetConnectionsNumber
  (JNIEnv *, jobject);

/*
 * Class:     zombie_core_raknet_RakNetPeerInterface
 * Method:    GetConnectionType
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_zombie_core_raknet_RakNetPeerInterface_GetConnectionType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
