/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zombie_core_raknet_RakVoice */

#ifndef _Included_zombie_core_raknet_RakVoice
#define _Included_zombie_core_raknet_RakVoice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    RVInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_RVInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    RVInitServer
 * Signature: (ZIIIIFFZ)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_RVInitServer
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jfloat, jfloat, jboolean);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    RVDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_RVDeinit
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetComplexity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakVoice_GetComplexity
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    SetComplexity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_SetComplexity
  (JNIEnv *, jclass, jint);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    RequestVoiceChannel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_RequestVoiceChannel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    CloseAllChannels
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_CloseAllChannels
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetBufferSizeBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakVoice_GetBufferSizeBytes
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetServerVOIPEnable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_raknet_RakVoice_GetServerVOIPEnable
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetSampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakVoice_GetSampleRate
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetSendFramePeriod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakVoice_GetSendFramePeriod
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetBuffering
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zombie_core_raknet_RakVoice_GetBuffering
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetMinDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_zombie_core_raknet_RakVoice_GetMinDistance
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetMaxDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_zombie_core_raknet_RakVoice_GetMaxDistance
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetIs3D
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_raknet_RakVoice_GetIs3D
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    CloseVoiceChannel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_CloseVoiceChannel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    ReceiveFrame
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_raknet_RakVoice_ReceiveFrame
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    SendFrame
 * Signature: (JJ[BJ)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_SendFrame
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    SetLoopbackMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_SetLoopbackMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    SetVoiceBan
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_SetVoiceBan
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    SetChannelsRouting
 * Signature: (JZ[IS)V
 */
JNIEXPORT void JNICALL Java_zombie_core_raknet_RakVoice_SetChannelsRouting
  (JNIEnv *, jclass, jlong, jboolean, jintArray, jshort);

/*
 * Class:     zombie_core_raknet_RakVoice
 * Method:    GetChannelStatistics
 * Signature: (J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_zombie_core_raknet_RakVoice_GetChannelStatistics
  (JNIEnv *, jclass, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
