/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zombie_core_znet_ZNet */

#ifndef _Included_zombie_core_znet_ZNet
#define _Included_zombie_core_znet_ZNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zombie_core_znet_ZNet
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zombie_core_znet_ZNet_init
  (JNIEnv *, jclass);

/*
 * Class:     zombie_core_znet_ZNet
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_zombie_core_znet_ZNet_setLogLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
